### ISSUE TITLE
More intelligent auto-pause on app going to background

### ISSUE THREAD

**Issue by anohren** [OdyseeTeam/odysee-ios#226]
When the app state changes to background the currently playing video always pauses. 

A more streamlined experience would be to not auto-pause on entering background in the following two cases:

1. When the video is playing in the mini player. The visual content is clearly deprioritized by the user, so it's reasonable that they want to continue listening to the audio. After all, the main purpose of the mini player is to allow the user to direct visual focus elsewhere in the app. 
2. After the user has earlier resumed playback of the current video while the app was in the background; the intent of listening to the video has been made clear earlier. This is also the behavior of some built in iOS apps.

Benefits:
- No need to turn off and then on the screen just to resume playback before turning the screen off again. 
- No need to open control center after pressing the home button, then wait for playback to auto-pause just to immediately resume playback and close control center again.

**Comment by tzarebczan** [comment]
Thanks for the feedback and opening the issue @anohren ! 

Was able to reproduce both of these. I agree with the suggestions.
