### ISSUE TITLE
Don't auto play videos if a video is already playing

### ISSUE THREAD

**Issue by anohren** [OdyseeTeam/odysee-ios#240]
When entering the details view of a video it starts playing automatically. This isn't desirable when a video is playing in the mini player. Navigation should not have side effects like aborting what you've already decided to watch/listen to.

**Comment by anohren** [comment]
It could be argued that it's not desirable at all, since you can't read the description without entering the detail view. 

If you're e.g. listening to music while browsing and deciding whether to watch something then you currently have to choose between either a) interrupted playback of what you've already decided to listen to (the music), or b) not reading *any* video description.

**Comment by tzarebczan** [comment]
Similar to the Android app we're working on, we want to make this a 3 way setting: 1) always, 2) only when not playing, 3) never

**Comment by anohren** [comment]
Sounds reasonable, if \#\2 applies to any app (I won't know how to escape # to not link internally on GitHub...)

**Comment by ktprograms** [comment]
@anohren What would the intended UX be if a user clicks on another video, but doesn't start it playing, then wants to go back to the first video? Currently the video view slides in/out, and it gets replaced when switching videos.

Should adding a new video add to the stack?
Maybe once the next video is started the first video can be removed from the stack such that when dismissing there's only one video to dismiss?

**Comment by anohren** [comment]
> What would the intended UX be if a user clicks on another video, but doesn't start it playing, then wants to go back to the first video?

I imagine that the mini player is already active at that point and that you tap on it to bring up the active (first) video. To me the video player/page looks modal, currently. 



> Should adding a new video add to the stack?

Here I'm not sure exactly what "adding a new video" refers to. Do you mean navigating to a new video?

I'm also a bit unsure about whether you mean "stack" as in the usual navigation stack or an invisibly maintained stack of some sort. If the former, then I have trouble visualizing the stack since to me neither the mini player nor the regular video page seem to have regular navigation stack behavior (?)

I think I'd find it a bit disorienting if the decision of whether a video page is opened in the navigation stack or in the (current) "modal" video view were context sensitive. But yes, I'd expect the second video to be pushed onto the navigation stack. I'd expect the first one to as well, I think, and only become modal if I were to access it through the mini player after having navigated away.

**Comment by ktprograms** [comment]
> I imagine that the mini player is already active at that point and that you tap on it to bring up the active (first) video. To me the video player/page looks modal, currently.

Do you mean that the miniplayer should be kept even on the video viewer page?

> Here I'm not sure exactly what "adding a new video" refers to. Do you mean navigating to a new video?

Yes

> I'm also a bit unsure about whether you mean "stack" as in the usual navigation stack or an invisibly maintained stack of some sort. If the former, then I have trouble visualizing the stack since to me neither the mini player nor the regular video page seem to have regular navigation stack behavior (?)

It slides in from the bottom and is closed by swiping down, so I'm wondering if it should be some kind of stack where you can go back to a previous video.

> I think I'd find it a bit disorienting if the decision of whether a video page is opened in the navigation stack or in the (current) "modal" video view were context sensitive. But yes, I'd expect the second video to be pushed onto the navigation stack. I'd expect the first one to as well, I think, and only become modal if I were to access it through the mini player after having navigated away.

I don't quite get what you mean.

**Comment by anohren** [comment]
> Do you mean that the miniplayer should be kept even on the video viewer page?

I think that is the most straightforward behavior compared to the current behavior if you want to open up for allowing users to play one video while also being able to navigate to other video pages. Otherwise, if there weren't even the mini player, you'd be left with only the audio and no visual indication that another video is playing in the background. 

Ok, I think I understand what you mean. A separate, always accessible stack of video pages with a max depth of 2. That doesn't correspond well to my mental model from most other apps, but then again I don't use the YouTube app which has probably established the strongest precedent 
and expectations of how an app like this should behave. Maybe it's a good idea to fulfill YouTube users' UI expectations if you want to provide a frictionless experience? I should probably take a look myself...

> I don't quite get what you mean

You can disregard that. I guessed wrongly that you wanted to push video pages onto the navigation stack, but only if another video was already playing. 

I think I personally *would* like video pages to simply be put on top of the navigation stack, just like content views in other apps, and to receive no special treatment unless I've started playback *and* navigated back (at which point it is preserved by transitioning to e.g. a mini player). In that case it'd be quite natural for the mini player to be visible while navigating to other video pages. Right now they feel like a modal singleton to me.  

I don't know if I'm answering your question at all now, but that's comes to me off the top of my head.

**Comment by ktprograms** [comment]
The YouTube app doesn't even have any confirmation, and only the currently playing video is available in its miniplayer.

I guess if the mini player is visible on video pages, there's no need for the multiple "stack" of video views, since the currently playing video will always be accessible.
Then you can navigate around looking for your next video, and click the miniplayer to go back to the currently playing video.

However, once the next video has been started, would you want there to be any way to get back to the previous video? This will have to change the navigation flow quite a lot, so if it isn't strictly necessary I'd just do the "miniplayer always visible" change.

**Comment by anohren** [comment]
> However, once the next video has been started, would you want there to be any way to get back to the previous video?

I can't think of any particularly compelling reason for that. When I decide to watch something else then I signal that I'm done with the current video. 

That's not to say that playback history lists a la iOS Music app don't have value, should you choose to add one in the future.

**Comment by tzarebczan** [comment]
We should consider adding a stack history in the future so that the back button would work, but miniplayer access is fine for now. Thank you again @anohren !

**Comment by ktprograms** [comment]
If YouTube is the "gold standard" of video apps, I can happily say that with #378, we will have well surpassed that. (YouTube has a miniplayer but as soon as you open something else it goes away 🙄 )

@anohren The behaviour I've implemented for #378 is:
- If nothing is playing, immediately start playing.
- If another app is playing, immediately start playing. This is consistent with Apple Developer app and YouTube app.
- Miniplayer stays visible if opening another file.
- If miniplayer is visible, don't immediately start playing.
- Clicking play button removes miniplayer.
- Clicking miniplayer goes to that file.

Is the three-way setting of 1) always, 2) only when not playing, 3) never still necessary with this behaviour?

**Comment by anohren** [comment]
Nice work. I hope it will be received as an improvement!



> * If another app is playing, immediately start playing. This is consistent with Apple Developer app and YouTube app.

This one's interesting. While YouTube actually auto plays when navigating to a video page, the Developer app doesn't (for me). That means that YouTube has a legitimate reason to stop previous playback, while the fact that the Developer app does the same is best viewed as a bug; there's no good reason for it from a user perspective. 

Whether or not videos actually should auto play upon navigation — the way they do in the YouTube app — is perhaps not so much a design decision as a business decision. It reduces friction of consumption, while it's a bit harder to argue that it's expected behavior. 

Regardless, looking forward to try it out.
