### ISSUE TITLE
Magic Link doesn't deeplink to the iOS app, it just logs in on the default browser

### ISSUE THREAD

**Issue by tysheaff** [OdyseeTeam/odysee-ios#242]
Flow:

1. Click "Log in" on the signup page
2. Enter email and hit "Continue"
3. Click "Use Magic Link"
4. Open email and click "Sign in to your account" button
5. It opens my default browser instead of the Odysee app itself

I'm using iOS Gmail client, I can try out other email flows to see if this is a universal issue. After logging in with the magic link on my default browser and navigating back to the app, my app was logged in (I still need to investigate at a code level why this is the case), but it was a confusing UX flow, would be best to directly deep-link if it's feasible.

**Comment by akinwale** [comment]
This is the expected behaviour.
