### ISSUE TITLE
Smaller phone > Signup screen looks broken

### ISSUE THREAD

**Issue by tsheaff** [OdyseeTeam/odysee-ios#248]
iPod Touch 7th Gen simulator:

![Screen Shot 2021-09-23 at 2 49 30 PM](https://user-images.githubusercontent.com/1238684/134602044-6cdafaa8-c4fd-4449-8efe-085233af4fc8.png)

There's also this version without the bar at the bottom (still broken):

![Screen Shot 2021-09-23 at 2 50 48 PM](https://user-images.githubusercontent.com/1238684/134602087-0998a2ba-797b-44a3-a128-1df9ae6a8c2f.png)

**Comment by tzarebczan** [comment]
This should be fixed in next release
