### ISSUE TITLE
Login action showed "create channel" flow instead

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-ios#263]
I logged into the app for the first time using an existing account, and after approving the Magic Link, it routed me to the "channel creation" dialog.  I think that should only appear for Sign Up.

**Comment by akinwale** [comment]
This is intended. The channel creation step will show up if there are no channels associated with your account.

**Comment by infinite-persistence** [comment]
Yup, by "an existing account", I meant an old account that's already Following some channels.
I just tried the steps again, but now it is showing the "Sync YT" step on login instead, which I have also rejected long ago.

Feels odd that I need to go through the same steps just because I'm using a new app in a new app platform.

**Comment by akinwale** [comment]
I understand what you mean. This is mostly due to the fact that these states are only checked / stored on the device.
