### ISSUE TITLE
Sign Up doesnt work

### ISSUE THREAD

**Issue by johnwaldo** [OdyseeTeam/odysee-ios#264]
Hello, having issues signing up using the iOS app. The 'sign up' button is overlayed on top of both email and password fields.

iOS 14.9.3
App: 0.5.10

Screenshot attached.

Suggestion would be that once I click 'sign up' the logo goes away, user email + password fields are expanded to fit the screen so its easier for the user signing up to see what they are inputting into the field. Clear and easily accessible sign up button to initiate registration placed below the fields.
![Attachment_1643664618834060](https://user-images.githubusercontent.com/13523483/151876615-9923c460-6cc3-4e60-9855-823a8a3e0cc6.JPG)

**Comment by tzarebczan** [comment]
Sorry to hear. Which device are you on? Does closing the keyboard help? 

In the meantime you can try odysee.com on your mobile browser if you can't sign up.

**Comment by johnwaldo** [comment]
Thank you for checking in. 

iPhone 10.

I tried swiping down on the keyboard to push out of the way, also trying clicking back into the view portal. Neither worked. It actually gets worse if auto fill fields populate into the keyboard. If they do, you are really unable to see the input fields.

**Comment by tzarebczan** [comment]
This will be fixed in the next release
