### ISSUE TITLE
Mini player video shows up in live stream view after app backgrounded in unrelated live stream view

### ISSUE THREAD

**Issue by anohren** [OdyseeTeam/odysee-ios#298]
1. Play a video in the mini player
2. Enter another video that is also marked as a live stream (that ended two days ago in this case, and furthermore wasn't playable — unresponsive play button over a black screen)
3. Background the app
4. Foreground the app. The video that played in the mini player is now shown in the live view above a completely unrelated chat log.

You'll also find that tapping the mini player after this will take you to the live view, again associating the video with an unrelated chat log.

**Comment by tzarebczan** [comment]
Thank you for the report!
