### ISSUE TITLE
Description field below videos doesn't let you click links

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-ios#323]
It would be really useful if links in the description below videos were directly clickable. Ideally this would use the default browser to view the links rather than rendering within the app.

Even being able to select text to copy & paste would be a good start. Currently you cannot interact with any of the text in the description.

This works fine on the web version of Odysee, however the functionality is lacking in the iOS app.

**Comment by ktprograms** [comment]
This has already been implemented in #303, and should be available in the next release of the Odysee iOS app.
