### ISSUE TITLE
commenting issues on channel page

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#336]
From KP:

- [ ]  I can't seem to change the channel to comment in a Channel Page's discussion section.

- [ ] Also, it crashes when I tap on my name in that page. 

He thinks it may be something with his account, so need to repro first.

**Comment by infinite-persistence** [comment]
> _What do you mean by "can't change the channel to comment"?_

The "Comment as @xxx" should be a dropdown for users to select the channel to comment as, but it seems like just a text.

**Comment by ktprograms** [comment]
Ah, I see. Would making it link/button coloured be okay?

**Comment by ktprograms** [comment]
The UI is the same for all the comment areas as it uses the same view controller.

**Comment by infinite-persistence** [comment]
Yeah, I'm not seeing it selectable in any place.

> _Ah, I see. Would making it link/button coloured be okay?_

Should be fine, as long as consistent everywhere like Tom mentioned.
