### ISSUE TITLE
Support default channel

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#371]
```
        "settings": {
          "active_channel_claim": "cb7ea953be131d156a780ff400414a187123e589",```
          

Support both getting and setting via preferences

**Comment by ktprograms** [comment]
Is `active_channel_claim` where the default channel is? On the android app it seems to be using the `default_channel_name` key from `AccountManager.getUserData`

**Comment by tzarebczan** [comment]
yep, we have it stored in the wallet data, so it should get/set using that.
