### ISSUE TITLE
Bring back full screen mode

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-ios#382]
In the latest update 0.6.5 you can no longer full screen a video. This makes it really hard to watch anything with small details like board repair videos.

**Comment by tzarebczan** [comment]
Sorry about that! We'll get it fixed soon...

**Comment by robd003** [comment]
Awesome, thanks for replying so quickly @tzarebczan

**Comment by robd003** [comment]
You guys rock for knocking out the fix so quickly. https://github.com/OdyseeTeam/odysee-ios/commit/a115a8dd0e465307aa2b32f93ccf49fe6b77445d

**Comment by tzarebczan** [comment]
Just waiting on apple approval , should be out anyday...

**Comment by akinwale** [comment]
0.6.6 which contains the fix is now live on the App Store.

**Comment by robd003** [comment]
@tzarebczan Is there a way to get an invite to the Apple TestFlight betas?

**Comment by tzarebczan** [comment]
Yes, i can add you. Email me your email at tom@odysee.com
