### ISSUE TITLE
text wrapping in posts 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#405]
![image](https://user-images.githubusercontent.com/8120721/196531988-13ea309e-d60b-427c-bfaa-50c9226bbc8f.png)

https://odysee.com/@Odysee:8/memberships:9

**Comment by akinwale** [comment]
Fixed in https://github.com/OdyseeTeam/odysee-ios/commit/9949673982e6e7b17b30b59c2a628c5587bd001e.
