### ISSUE TITLE
filter unlisted content + make sure to filter future scheduled

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#415]
- [ ] Unlisted content will have this tag: c:unlisted. Add to not tags
- [ ] verify that claim searches do a release time < now()

**Comment by ktprograms** [comment]
@tzarebczan For lighthouse searches it isn't possible to restrict release time < now, right?

**Comment by tzarebczan** [comment]
there isn't but I'll work on the lighthouse changes to not return these at all this week.
