### ISSUE TITLE
Odysee crashes when opening the app

### ISSUE THREAD

**Issue by AxoloCrypt** [OdyseeTeam/odysee-ios#429]
Odysee version: 0.6.13
IOS 16.1.2 

I have been struggling with the Odysee app for a few days.
Whenever I try to open the app, it crashes immediately. I have already uninstalled and reinstalled it, but the problem persists.

https://user-images.githubusercontent.com/98765502/214071139-67f469d1-5273-4b98-b0c0-7f274bbaca3d.MOV

**Comment by tzarebczan** [comment]
Does uninstalling and reinstalling the app help? Did it work on a precious version of the os?

**Comment by AxoloCrypt** [comment]
> Does uninstalling and reinstalling the app help? Did it work on a precious version of the os?

Uninstalling and reinstalling didn't solve the problem. It worked on previous versions of the os and
after moving to iOS 16.1.2, but the crashes suddenly appeared.

**Comment by tzarebczan** [comment]
Thanks for the info, we're still looking into it. 

What language is your phone set to?

**Comment by tzarebczan** [comment]
@AxoloCrypt can you confirm the latest update works now?

**Comment by AxoloCrypt** [comment]
> @AxoloCrypt can you confirm the latest update works now?

Yes! It works now, thank you so much.
