### ISSUE TITLE
Was this app taken down from the app store?

### ISSUE THREAD

**Issue by sallyFoster** [OdyseeTeam/odysee-ios#438]
And if so, could you please release the IPA files here for side-loading it?

**Comment by tzarebczan** [comment]
Shouldn't be, are you not seeing it?

**Comment by sallyFoster** [comment]
https://github.com/OdyseeTeam/odysee-ios/assets/104597302/f9f152a4-758f-4a5d-a55f-0b123c60320c

**Comment by tzarebczan** [comment]
We'll take a look, thank you. Definitely didn't receive any notifications.

**Comment by sallyFoster** [comment]
@tzarebczan Thanks!

Also from another angle:

https://github.com/OdyseeTeam/odysee-ios/assets/104597302/1f5198d0-d2a0-49bd-b445-5dfaec1c4a35

**Comment by tzarebczan** [comment]
Thank you again for bringing this to our attention. Looks like the developer program failed to renew recently due to an old card, and main account was linked to someone not with the company anymore.

Just renewed it, so it should be back on the store very soon!

**Comment by tzarebczan** [comment]
I see it there now, woohoo!
