### ISSUE TITLE
Bring back iPad support 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#6]
Make it work well on Ipad and fix any crashing issues (i.e. one when you go to the share dialog).

**Comment by robster7674** [comment]
Any ETA on getting iPad support? On iPad Pro 2021 12.9 inch it is not a very user-friendly experience to use the app.

**Comment by ktprograms** [comment]
For now let's focus on single controller and single window, just change the UI to work better on large screens. Also no "Supports multiple windows" as even though it mostly works, things like fully closing the app (from app switcher) causes playback to stop and other windows to lose state.

Blockers for iPad support:
- [ ] Share button crash
- [ ] Increase height of media view
- [ ] (Maybe) increase font size in Channel about page
- [ ] Livestreaming camera view not filling whole screen (maybe related to split screening before)

@tzarebczan @akinwale Anything else to add?
