### ISSUE TITLE
Upload flow suggestions / bugs

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-ios#84]
- [x] auto fill deposit at 0.001
- [x] selection ratio/crop for thumbnail seems off - very squarish
- [x] duplicate URL detection, or handling of duplicate publishes (stream create, ensure edits work)
- [x] Can't upload if bid 0, no indication. 
- [x] handle pending state
- [x] check balance vs bid (on edit, make sure to check existing bid + difference)

**Comment by akinwale** [comment]
> Can't upload if bid 0, no indication.
An error is displayed if this happens, but for some reason, it doesn't show up on smaller screens (as we've tested). I am investigating a solution for this.
