### ISSUE TITLE
Bluetooth remote commands (play / pause) often ignored

### ISSUE THREAD

**Issue by anohren** [OdyseeTeam/odysee-ios#99]
After locking the screen while playing a video the video often stops playing. When I want to continue listening to the audio I press the play/pause button on whichever Bluetooth headset is connected at the time. More often than not the command is ignored — playback doesn't resume. 

Waking the screen and resuming with the lock screen media controls almost always works, suggesting that either the app regularly transitions to a state where it stops responding to some remote commands (e.g. toggle play/pause) but not others (e.g. play, pause), or, alternatively, that an awake lock screen makes it behave differently. 

Probably not the latter since the Bluetooth play/pause button still doesn't work at the lock screen. In fact, Bluetooth play/pause randomly doesn't work in-app either.

**Comment by ktprograms** [comment]
@anohren When the next version releases with the fix to PiP/Now playing can you please test this again?

**Comment by anohren** [comment]
I've tried it out with the new version and it doesn't react at all to play, pause, play/pause commands (I'm unsure exactly which events my headset is sending but all three should reasonably be bound to the same thing in-app).

**Comment by ktprograms** [comment]
Weirdly, this works with my bluetooth earphones, but not my wired earphones. I'll try and see what's the problem. Thanks for reporting!

**Comment by anohren** [comment]
This is working pretty well now!

Sometimes the player seems to end up in a state where the toggle command results in pausing and immediately starting playback again, making it impossible to pause with the command (but not to resume with it).

**Comment by ktprograms** [comment]
Do you know what seems to cause this behaviour? I can't seem to reproduce it with just pressing toggle while playing a video.

**Comment by anohren** [comment]
I'll keep a lookout for a pattern

**Comment by ktprograms** [comment]
Thanks. I was also having it happen when running with some changes I'm working on, and it seems to be because the command obversers are being added twice.

@akinwale I looked at the code, and it seems like `displayClaim()` is getting called twice, once in `viewDidLoad()` and once (indirectly) in `viewDidAppear()` (from `showClaimAndCheckFollowing()`).

**Comment by anohren** [comment]
> the command obversers are being added twice

That's the assumption I made as well from the observed behavior. Nice to see that you came to the same conclusion.
